parameters:
    brother_contacts.model.entry.class: Brother\ContactsBundle\Entity\Entry
    brother_contacts.manager.entry.class: Brother\ContactsBundle\Entity\EntryManager
services:
    brother_contacts.entity_manager:
        alias: 'doctrine.orm.entity_manager'

    brother_contacts.entry_manager:
        class: %brother_contacts.manager.entry.class%
        arguments:
            - '@event_dispatcher'
            - '@brother_contacts.entity_manager'
            - %brother_contacts.model.entry.class%
